import os


            
            
class FileChecker:
    def __init__(self, root_dir, verbose=False, excludes=[]):
        self.root_dir = root_dir
        self.excludes = excludes
        self.verbose = verbose
        self.missing_files = []
        self.empty_files = []
        
    def check_missing_indexes(self):
        for root, dirs, files in os.walk(self.root_dir):
            if "index.md" not in files:
                if not any([exclude in root for exclude in self.excludes]):
                    self.missing_files.append(root)
                    if self.verbose:
                        print("No index.md file found in " + root)
        print("Found " + str(len(self.missing_files)) + " missing files")
        return self.missing_files
    
    def check_for_empty_files(self):
        for root, dirs, files in os.walk(self.root_dir):
            for file in files:
                if file.endswith(".md"):
                    if os.stat(os.path.join(root, file)).st_size == 0:
                        print("Empty file found: " + os.path.join(root, file))
                        self.empty_files.append(os.path.join(root, file))
        print("Found " + str(len(self.empty_files)) + " empty files")
        return self.empty_files
    
    def fix(self):
        for missing_file in self.missing_files:
            with open(os.path.join(missing_file, "index.md"), "w") as f:
                self.write_file_content(f, missing_file)
        for empty_file in self.empty_files:
            with open(empty_file, "w") as f:
                self.write_file_content(f, empty_file)
                
    def write_file_content(self, f, file):
        f.write("---\n")
        f.write("title: " + file.split("/")[-1] + "\n")
        f.write("---\n")
        f.write("\n")
        f.write("This is a stub for the " + file.split("/")[-1] + " section.\n")
        f.write("\n")
        f.write("Please add content to this section.\n")
        f.write("\n")
        f.write("If you are seeing this message, please contact the site administrator.\n")
        f.write("\n")
        f.write("Thank you!\n")
        f.write("\n")
        f.write("This message was automatically generated by the file_check.py script.\n")
        f.write("\n")
                
    def has_auto_gen_file(self):
        """For the CI pipeline
           Returns true if any auto-generated files are found => Should not build the site
        """
        has_auto_gen_file = False
        gen_files = []
        for root, dirs, files in os.walk(self.root_dir):
            for file in files:
                if file.endswith(".md"):
                    with open(os.path.join(root, file), "r") as f:
                        if "This message was automatically generated by the file_check.py script." in f.read():
                            has_auto_gen_file = True
                            gen_files.append(os.path.join(root, file))
        print("Found " + str(len(gen_files)) + " auto-generated files")
        return has_auto_gen_file, gen_files
            
            
if __name__ == "__main__":
    # Get arguments
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--auto-fix", action="store_true")
    parser.add_argument("--root-dir", default="./docs")
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--excludes", nargs="*", default=["assets"])
    parser.add_argument("--strict", action="store_true") # For the CI pipeline -> returns false if no errors found
    args = parser.parse_args()
    file_checker = FileChecker(args.root_dir, excludes=args.excludes, verbose=args.verbose)
    missing_files = file_checker.check_missing_indexes()
    empty_files = file_checker.check_for_empty_files()
    if args.auto_fix:
        file_checker.fix()
        print("Missing files fixed")
    else:
        print("Missing files not fixed")
        print("To fix, run with --auto-fix")
        if(len(missing_files) > 0) or (len(empty_files) > 0):
            exit(1)
    if args.strict:
        has_auto_gen_file, files = file_checker.has_auto_gen_file()
        if has_auto_gen_file:
            print("Auto-generated files found")
            print("Please remove them before building the site")
            print("Files found:")
            for file in files:
                print(file)
            exit(1)
        else:
            print("No auto-generated files found")
            exit(0)

    